<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>PCSentinel.Analysis</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PCSentinel.Core\PCSentinel.Core.csproj" />
  </ItemGroup>

</Project>
